"""Command-line interface for nooprompter"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_cli.ipynb.

# %% ../nbs/04_cli.ipynb 1
from __future__ import annotations

# %% auto 0
__all__ = ['init', 'config_cmd', 'tags', 'build', 'chelp']

# %% ../nbs/04_cli.ipynb 4
from pathlib import Path

from fastcore.script import call_parse


# %% ../nbs/04_cli.ipynb 5
from .config import find_config
from .config import load_config
from .config import validate_config
from .tags import discover_tags_in_templates
from .templates import process_all
from .templates import process_vendor


# %% ../nbs/04_cli.ipynb 9
@call_parse
def init(
    force: bool = False  # Overwrite existing config
):
    "Initialize nooprompter config from default template"
    config_file = Path('.nooprompter.yml')
    
    if config_file.exists() and not force:
        print(f"Config already exists: {config_file}")
        print("Use --force to overwrite")
        return 1
    
    try:
        from importlib.resources import files
        default_yml = files('nooprompter').joinpath('static/default.nooprompter.yml')
        with default_yml.open('r') as src:
            config_file.write_text(src.read())
        
        print(f"✓ Created {config_file}")
        print("\nNext steps:")
        print("  1. Edit .nooprompter.yml to customize tags")
        print("  2. Create templates/ directory structure")
        print("  3. Run 'nooprompter build' to process templates")
        return 0
    except Exception as e:
        print(f"Error: Could not create config file: {e}")
        return 1

# %% ../nbs/04_cli.ipynb 12
@call_parse
def config_cmd(
    validate: bool = False  # Validate configuration
):
    "Show and optionally validate configuration"
    cfg = load_config()
    config_path = find_config()
    
    # Show config info
    print(f"Config: {config_path if config_path else '(using defaults)'}")
    print(f"Tags: {len(cfg.get('tags', {}))}")
    
    # List template vendors
    templates = cfg.get('templates', {})
    vendor_count = len([k for k in templates.keys() if k != 'meta'])
    print(f"Vendors: {vendor_count}")
    for key in templates.keys():
        if key == 'meta':
            print(f"  • meta (project files)")
        else:
            print(f"  • {key}")
    
    # Validate if requested
    if validate:
        is_valid, errors = validate_config(cfg)
        if is_valid:
            print("\n✓ Configuration is valid")
        else:
            print("\n✗ Configuration errors:")
            for error in errors:
                print(f"  - {error}")
            return 1
    
    return 0

# %% ../nbs/04_cli.ipynb 15
@call_parse
def tags(
    path: str|None = None  # Path to template file or directory
):
    "Discover tags in templates"
    config = load_config()
    
    # Find base path from config location
    config_path = find_config()
    base_path = config_path.parent if config_path else Path.cwd()
    
    if path:
        # Scan specific path (absolute or relative to cwd)
        target = Path(path)
        if not target.exists():
            print(f"Error: Path not found: {path}")
            return 1
        
        if target.is_file():
            from nooprompter.tags import discover_tags_in_file
            found_tags = discover_tags_in_file(target)
            print(f"Tags in {path}:")
        else:
            found = discover_tags_in_templates(target)
            found_tags = set()
            for file_tags in found.values():
                found_tags.update(file_tags)
            print(f"Tags in {path}:")
    else:
        # Scan templates directory relative to config location
        templates_dir = base_path / 'templates'
        if not templates_dir.exists():
            print(f"Templates directory not found at {templates_dir}")
            print("Create 'templates/' or specify path with --path")
            return 1
        
        found = discover_tags_in_templates(templates_dir)
        found_tags = set()
        for file_tags in found.values():
            found_tags.update(file_tags)
        print(f"Tags in {templates_dir.relative_to(base_path)}:")
    
    if not found_tags:
        print("  (no tags found)")
        return 0
    
    # Show tags with status
    defined_tags = config.get('tags', {})
    for tag in sorted(found_tags):
        if tag in defined_tags:
            print(f"  <{tag}> ✓")
        else:
            print(f"  <{tag}> ✗ (not defined)")
    
    return 0

# %% ../nbs/04_cli.ipynb 18
@call_parse
def build(
    vendor: str|None = None,  # Specific vendor to build (e.g., 'Cursor')
    dry_run: bool = False  # Show what would be done without doing it
):
    "Build templates from source"
    config = load_config()
    
    # Find base path from config location
    config_path = find_config()
    base_path = config_path.parent if config_path else Path.cwd()
    
    if dry_run:
        print("DRY RUN - No files will be created")
    
    try:
        if vendor:
            print(f"Building {vendor} templates...")
            if not dry_run:
                files = process_vendor(config, vendor, base_path)
                print(f"✓ Processed {len(files)} files")
                for f in files:
                    print(f"  {f.relative_to(base_path)}")
        else:
            print("Building all templates...")
            if not dry_run:
                results = process_all(config, base_path)
                total = sum(len(files) for files in results.values())
                print(f"✓ Processed {total} files across {len(results)} sections")
                for section, files in results.items():
                    print(f"  {section}: {len(files)} files")
        
        if not dry_run:
            print("\n✓ Build complete!")
        return 0
    except Exception as e:
        print(f"Error during build: {e}")
        return 1

# %% ../nbs/04_cli.ipynb 20
@call_parse
def chelp():
    "Show help for all console scripts"
    from fastcore.xtras import console_help
    console_help('nooprompter')
