"""Configuration loading and validation for noopromptersss"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_config.ipynb.

# %% ../nbs/01_config.ipynb 1
from __future__ import annotations

# %% auto 0
__all__ = ['find_config', 'load_config', 'validate_config', 'get_tag', 'get_all_tags']

# %% ../nbs/01_config.ipynb 4
from importlib.resources import files
from pathlib import Path

import yaml


# %% ../nbs/01_config.ipynb 5
from pote.common import val_at
from pote.display import RenderJSON


# %% ../nbs/01_config.ipynb 8
_DEFAULT_CONFIG = {
    'templates': {
        'meta': {
            'path': ["meta/**/*.md", "meta/**/*.yml"]
        },
        'Cursor': {
            'path': [".cursor/rules/"]
        }
    },
    'tags': {
        'Project-Name': 'myproject',
        'User-Alias': 'user',
    },
    'general': {
        'ignore': [],
        'warn_missing_tags': True,
        'strict_mode': False,
        'max_recursion': 10,
        'preserve_timestamps': False
    }
}

def _load_default_config() -> dict:
    "Load default config from package resources"
    try:
        default_yml = files('nooprompter').joinpath('static/default.nooprompter.yml')
        with default_yml.open('r') as f: return yaml.safe_load(f)
    except Exception as e: return _DEFAULT_CONFIG

_DEFAULT_CONFIG = _load_default_config()

# %% ../nbs/01_config.ipynb 10
CONFIG_FILENAME = '.nooprompter.yml'

# %% ../nbs/01_config.ipynb 11
def find_config(start_path: str | Path = '.') -> Path | None:
    "Search up directory tree for .nooprompter.yml config file"
    current = Path(start_path).resolve()
    for parent in [current, *current.parents]:
        config_path = parent / CONFIG_FILENAME
        if config_path.exists(): return config_path
    return None

# %% ../nbs/01_config.ipynb 13
def load_config(path: str | Path = '.') -> dict:
    "Load and parse `CONFIG_FILENAME` config file, use defaults if not found"
    config, config_path = None, find_config(path)
    if config_path is not None: 
        with open(config_path, 'r') as f: config = yaml.safe_load(f)
    merged = _DEFAULT_CONFIG.copy()
    if config is not None:
        for key in config:
            if isinstance(config[key], dict) and key in merged:
                merged[key] = {**merged[key], **config[key]}
            else:
                merged[key] = config[key]
    return merged

# %% ../nbs/01_config.ipynb 16
def validate_config(config: dict) -> tuple[bool, list[str]]:
    "Validate config structure, return (is_valid, errors)"
    errors = []
    if 'tags' in config and not isinstance(config['tags'], dict):
        errors.append("'tags' section must be a dictionary")
    if 'templates' in config and not isinstance(config['templates'], dict):
        errors.append("'templates' section must be a dictionary")
    if 'general' in config and not isinstance(config['general'], dict):
        errors.append("'general' section must be a dictionary")
    return (len(errors) == 0, errors)

# %% ../nbs/01_config.ipynb 20
def get_tag(config: dict, tag_name: str, default: str | None = None) -> str:
    "Get tag value from config, with optional default"
    return val_at(config, f'tags.{tag_name}', default)  # type: ignore

# %% ../nbs/01_config.ipynb 22
def get_all_tags(config: dict) -> dict[str, str]:
    "Get all tags from config as a flat dictionary"
    return config.get('tags', {})
