"""Template file discovery and processing"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_templates.ipynb.

# %% ../nbs/03_templates.ipynb 1
from __future__ import annotations

# %% auto 0
__all__ = ['get_template_files', 'should_ignore', 'process_template', 'process_vendor', 'process_all']

# %% ../nbs/03_templates.ipynb 4
import fnmatch
import shutil
from pathlib import Path


# %% ../nbs/03_templates.ipynb 5
from .config import find_config
from .config import get_all_tags
from .config import load_config
from .tags import substitute_tags_in_file


# %% ../nbs/03_templates.ipynb 8
def get_template_files(source_dir: str | Path, extensions: list[str]) -> list[Path]:
    "Find all template files with specified extensions"
    source_dir = Path(source_dir)
    if not source_dir.exists(): return []
    files = []
    for ext in extensions:
        if not ext.startswith('.'): ext = f'.{ext}'
        files.extend(source_dir.rglob(f'*{ext}'))
    return [f for f in files if f.is_file()]


# %% ../nbs/03_templates.ipynb 10
def should_ignore(path: Path, ignore_patterns: list[str]) -> bool:
    "Check if path matches any ignore pattern"
    if not ignore_patterns: return False
    path_str = str(path)
    path_parts = path.parts
    for pattern in ignore_patterns:
        # Check full path match
        if fnmatch.fnmatch(path_str, pattern): return True
        # Check filename match
        if fnmatch.fnmatch(path.name, pattern): return True
        # Check if any path component matches
        if pattern in path_parts: return True
        # Check pattern match on any component
        if any(fnmatch.fnmatch(part, pattern) for part in path_parts): return True
    return False

# %% ../nbs/03_templates.ipynb 14
def process_template(
    src: Path,                         # Source template file
    dst: Path,                         # Destination file
    tags: dict[str, str],              # Tag substitution dictionary
    no_substitution: list[str]|None = None, # List of file patterns to copy without substitution
    **options                          # Options for substitute_tags
) -> Path:                             # Path to destination file
    "Process a single template file"
    if no_substitution is None: no_substitution = []
    should_copy_as_is = any(
        fnmatch.fnmatch(str(src), pattern) or fnmatch.fnmatch(src.name, pattern)
        for pattern in no_substitution
    )
    dst.parent.mkdir(parents=True, exist_ok=True)
    if should_copy_as_is: shutil.copy2(src, dst)
    else: substitute_tags_in_file(src, dst, tags, **options)
    return dst

# %% ../nbs/03_templates.ipynb 15
def process_vendor(
    config: dict,
    vendor_name: str,
    root_path: Path | None = None
) -> list[Path]:
    "Process all templates for a specific vendor"
    if root_path is None: root_path = Path.cwd()
    
    templates = config.get('templates', {})
    if vendor_name not in templates:
        raise ValueError(f"Vendor '{vendor_name}' not found in config")
    
    vendor_config = templates[vendor_name]
    
    # Convention: source is templates/{vendor_name}/
    source_dir = root_path / 'templates' / vendor_name
    
    # Special case for meta - hardcoded destination
    if vendor_name == 'meta':
        dest_dir = root_path / 'meta'
    else:
        dest = vendor_config.get('dest')
        if not dest:
            raise ValueError(f"Vendor '{vendor_name}' missing 'dest' configuration")
        dest_dir = root_path / dest
    
    # Default extensions for text files
    extensions = ['.md', '.mdc', '.txt', '.yml', '.yaml']
    
    tags = config['tags']
    general = config['general']
    ignore_patterns = general.get('ignore', [])
    
    template_files = get_template_files(source_dir, extensions)
    processed = []
    
    for src_file in template_files:
        if should_ignore(src_file, ignore_patterns):
            continue
        rel_path = src_file.relative_to(source_dir)
        dst_file = dest_dir / rel_path
        process_template(src_file, dst_file, tags)
        processed.append(dst_file)
    
    return processed

# %% ../nbs/03_templates.ipynb 16
def process_all(
    config: dict,
    root_path: Path | None = None
) -> dict[str, list[Path]]:
    "Process all configured templates"
    if root_path is None: root_path = Path.cwd()
    
    results = {}
    templates = config.get('templates', {})
    
    for vendor_name in templates:
        try:
            files = process_vendor(config, vendor_name, root_path)
            if files:
                results[vendor_name] = files
        except Exception as e:
            print(f"Warning: Failed to process {vendor_name}: {e}")
    
    return results
